---
#global settings
pid_dir: '~/.pg_chameleon/pid/'
log_dir: '~/.pg_chameleon/logs/'
log_dest: file
log_level: info
log_days_keep: 10
rollbar_key: ''
rollbar_env: ''

# type_override allows the user to override the default type conversion into a different one.
type_override:
  "tinyint(1)":
    override_to: boolean
    override_tables:
      - "*"

#postgres  destination connection
pg_conn:
  host: "127.0.0.1"
  port: "5432"
  user: "zabbix"
  password: "zabbix"
  database: "zabbix"
  charset: "utf8"

sources:
  mysql:
    db_conn:
      host: "127.0.0.1"
      port: "3306"
      user: "zabbix2"
      password: "zabbix"
      charset: 'utf8'
      connect_timeout: 10
    schema_mappings:
      zabbix: zabbix
    limit_tables:
#      - delphis_mediterranea.foo
    skip_tables:
#      - delphis_mediterranea.bar
    grant_select_to:
      - usr_readonly
    lock_timeout: "120s"
    my_server_id: 9277
    replica_batch_size: 10000
    replay_max_rows: 10000
    batch_retention: '1 day'
    copy_max_memory: "300M"
    copy_mode: 'file'
    out_dir: /tmp
    sleep_loop: 1
    on_error_replay: continue
    on_error_read: continue
    auto_maintenance: "disabled"
    gtid_enable: No
    type: mysql
#    skip_events:
#      insert:
#        - delphis_mediterranea.foo #skips inserts on the table delphis_mediterranea.foo
#      delete:
#        - delphis_mediterranea #skips deletes on schema delphis_mediterranea
#      update:
