name: Build and Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Docker Repository
      uses: bakaut/zbx2timescaledb@master
      with:
        name: bakaut/pgloader
        username: ${{ secrets.DOCKEHUB_USER }}
        password: ${{ secrets.DOCKEHUB_PASS }}
